// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNZ_pXGg8fmq4F5hz2vI0Fbyb8OYXf3M',
    appId: '1:844741231468:web:217c851547e3ed4275e949',
    messagingSenderId: '844741231468',
    projectId: 'whatsapp-clone-af023',
    authDomain: 'whatsapp-clone-af023.firebaseapp.com',
    storageBucket: 'whatsapp-clone-af023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAoifA3m1SJdkgqnxb-V-XW6S_kh-2dLo',
    appId: '1:844741231468:android:06a3a5f282061d7975e949',
    messagingSenderId: '844741231468',
    projectId: 'whatsapp-clone-af023',
    storageBucket: 'whatsapp-clone-af023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmeDPVhsXZgSKq1NGlguUokCEtuaqwWGQ',
    appId: '1:844741231468:ios:d66e56d9e12655e475e949',
    messagingSenderId: '844741231468',
    projectId: 'whatsapp-clone-af023',
    storageBucket: 'whatsapp-clone-af023.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmeDPVhsXZgSKq1NGlguUokCEtuaqwWGQ',
    appId: '1:844741231468:ios:9620bbf246ec461775e949',
    messagingSenderId: '844741231468',
    projectId: 'whatsapp-clone-af023',
    storageBucket: 'whatsapp-clone-af023.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
